/**
 * Regenerates src/templates-data.ts from the Blank Invoice Maker app's
 * template registry, by parsing the source files with the TypeScript AST
 * (no code execution — avoids path-alias resolution).
 *
 * Run:  npm run generate:templates
 * Point at the app with BIM_APP_DIR=/path/to/blank-invoice-maker (defaults to
 * a sibling ../blank-invoice-maker directory).
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const appDir = process.env.BIM_APP_DIR
  ? path.resolve(process.env.BIM_APP_DIR)
  : path.resolve(repoRoot, "..", "blank-invoice-maker");
const templatesDir = path.join(appDir, "src", "constants", "templates");
const outFile = path.join(repoRoot, "src", "templates-data.ts");

interface TemplateEntry {
  slug: string;
  name: string;
  title: string;
  description: string;
}

function propName(name: ts.PropertyName): string | undefined {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name)) return name.text;
  return undefined;
}

function strProp(obj: ts.ObjectLiteralExpression, key: string): string | undefined {
  for (const p of obj.properties) {
    if (!ts.isPropertyAssignment(p)) continue;
    if (propName(p.name) !== key) continue;
    const init = p.initializer;
    if (ts.isStringLiteralLike(init) || ts.isNoSubstitutionTemplateLiteral(init)) {
      return init.text;
    }
  }
  return undefined;
}

function stripSuffix(title: string): string {
  return title.replace(/\s*\|\s*Blank Invoice Maker\s*$/i, "").trim();
}

async function main() {
  const files = (await fs.readdir(templatesDir))
    .filter((f) => f.endsWith(".ts") && f !== "index.ts" && f !== "types.ts")
    .sort();

  const out: TemplateEntry[] = [];

  for (const file of files) {
    const text = await fs.readFile(path.join(templatesDir, file), "utf8");
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);

    for (const stmt of sf.statements) {
      if (!ts.isVariableStatement(stmt)) continue;
      for (const decl of stmt.declarationList.declarations) {
        if (!ts.isIdentifier(decl.name) || !decl.name.text.endsWith("Templates")) continue;
        if (!decl.initializer || !ts.isArrayLiteralExpression(decl.initializer)) continue;

        for (const el of decl.initializer.elements) {
          if (!ts.isObjectLiteralExpression(el)) continue;
          const slug = strProp(el, "slug");
          const name = strProp(el, "name");
          const title = strProp(el, "title");
          const description = strProp(el, "description");
          if (slug && name) {
            out.push({
              slug,
              name,
              title: stripSuffix(title ?? name),
              description: description ?? "",
            });
          }
        }
      }
    }
  }

  out.sort((a, b) => a.name.localeCompare(b.name));

  const header =
    `// AUTO-GENERATED by scripts/generate-templates.ts — do not edit by hand.\n` +
    `// Source: Blank Invoice Maker template registry (${out.length} templates).\n\n`;
  const body =
    `export interface TemplateInfo {\n` +
    `  slug: string;\n  name: string;\n  title: string;\n  description: string;\n}\n\n` +
    `export const templates: TemplateInfo[] = ${JSON.stringify(out, null, 2)};\n`;

  await fs.writeFile(outFile, header + body, "utf8");
  console.log(`Wrote ${out.length} templates to ${path.relative(repoRoot, outFile)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
