// AUTO-GENERATED by scripts/generate-templates.ts — do not edit by hand.
// Source: Blank Invoice Maker template registry (33 templates).

export interface TemplateInfo {
  slug: string;
  name: string;
  title: string;
  description: string;
}

export const templates: TemplateInfo[] = [
  {
    "slug": "auto-repair",
    "name": "Auto Repair",
    "title": "Free Auto Repair Invoice Template",
    "description": "Generate auto repair invoices for mechanic shops, mobile mechanics, and vehicle service centres. Free PDF download — no sign-up needed."
  },
  {
    "slug": "cleaning-service",
    "name": "Cleaning Service",
    "title": "Free Cleaning Service Invoice Template",
    "description": "Create professional cleaning service invoices for residential and commercial clients. Free PDF generator — no sign-up or watermark."
  },
  {
    "slug": "consulting",
    "name": "Consulting",
    "title": "Free Consulting Invoice Template",
    "description": "Create polished consulting invoices with our free template. Perfect for management consultants, IT consultants, and advisory firms."
  },
  {
    "slug": "contractor",
    "name": "Contractor",
    "title": "Free Contractor Invoice Template",
    "description": "Generate contractor invoices fast. Ideal for builders, electricians, plumbers, and trade professionals who need clean PDF invoices."
  },
  {
    "slug": "dj-entertainment",
    "name": "DJ & Entertainment",
    "title": "Free DJ Invoice Template",
    "description": "Create DJ and entertainment invoices for events, weddings, and parties. Free PDF download — no sign-up."
  },
  {
    "slug": "dog-walking",
    "name": "Dog Walking & Pet Sitting",
    "title": "Free Dog Walking Invoice Template",
    "description": "Create dog walking and pet sitting invoices for daily walks, overnight stays, and pet care. Free PDF download."
  },
  {
    "slug": "electrical",
    "name": "Electrical",
    "title": "Free Electrical Invoice Template",
    "description": "Create electrician invoices for wiring, panel upgrades, and lighting installations. Free PDF download — no sign-up."
  },
  {
    "slug": "event-planning",
    "name": "Event Planning",
    "title": "Free Event Planning Invoice Template",
    "description": "Create event planning invoices for coordination fees, vendor deposits, and event management. Free PDF download."
  },
  {
    "slug": "freelance",
    "name": "Freelance",
    "title": "Free Freelance Invoice Template",
    "description": "Create professional freelance invoices in seconds. Our free invoice generator is perfect for freelancers, consultants, and independent contractors."
  },
  {
    "slug": "freelance-bill",
    "name": "Freelance Bill",
    "title": "Freelance Bill Template",
    "description": "Generate a clean freelance bill for any type of independent work — design, development, consulting, or creative services."
  },
  {
    "slug": "freelance-writer",
    "name": "Freelance Writer",
    "title": "Freelance Writer Invoice Template",
    "description": "Create professional invoices for freelance writing work — blog posts, copywriting, ghostwriting, and editorial projects."
  },
  {
    "slug": "graphic-design",
    "name": "Graphic Design",
    "title": "Free Graphic Design Invoice Template",
    "description": "Create graphic design invoices for branding packages, logo concepts, and design projects. Free PDF download — no sign-up."
  },
  {
    "slug": "handyman",
    "name": "Handyman",
    "title": "Free Handyman Invoice Template",
    "description": "Create handyman invoices for repair jobs, maintenance work, and home improvement services. Free PDF invoice generator — no sign-up required."
  },
  {
    "slug": "hvac",
    "name": "HVAC",
    "title": "Free HVAC Invoice Template",
    "description": "Generate HVAC invoices for heating, ventilation, and air conditioning services. Free PDF invoice generator — no sign-up required."
  },
  {
    "slug": "independent-contractor",
    "name": "Independent Contractor",
    "title": "Free Independent Contractor Invoice Template",
    "description": "Generate independent contractor invoices for 1099 work, contract projects, and self-employed services. Free PDF download — no sign-up required."
  },
  {
    "slug": "landscaping",
    "name": "Landscaping",
    "title": "Free Landscaping Invoice Template",
    "description": "Create landscaping invoices for lawn care, garden design, and hardscaping projects. Free PDF generator — no account needed."
  },
  {
    "slug": "marketing",
    "name": "Marketing",
    "title": "Free Marketing Invoice Template",
    "description": "Create marketing and advertising invoices for campaigns, retainers, and project work. Free PDF download."
  },
  {
    "slug": "painting",
    "name": "Painting",
    "title": "Free Painting Invoice Template",
    "description": "Create painting contractor invoices for interior and exterior projects. Free PDF download — no sign-up or watermark."
  },
  {
    "slug": "personal-trainer",
    "name": "Personal Trainer",
    "title": "Free Personal Trainer Invoice Template",
    "description": "Create personal training invoices for sessions, packages, and nutrition plans. Free PDF download — no sign-up."
  },
  {
    "slug": "photography",
    "name": "Photography",
    "title": "Photography Invoice Generator",
    "description": "Invoice for photography sessions, events, and print sales. Our free template covers deposits, packages, and extras."
  },
  {
    "slug": "plumbing",
    "name": "Plumbing",
    "title": "Free Plumbing Invoice Template",
    "description": "Create professional plumbing invoices for pipe repairs, installations, and emergency service calls. Free PDF download — no sign-up required."
  },
  {
    "slug": "pressure-washing",
    "name": "Pressure Washing",
    "title": "Free Pressure Washing Invoice Template",
    "description": "Create pressure washing invoices for driveways, decks, and commercial exterior cleaning. Free PDF download."
  },
  {
    "slug": "proforma",
    "name": "Proforma Invoice",
    "title": "Free Proforma Invoice Template",
    "description": "Create professional proforma invoices for international trade and advance billing. Free PDF download with no sign-up required."
  },
  {
    "slug": "property-management",
    "name": "Property Management",
    "title": "Free Property Management Invoice Template",
    "description": "Create property management invoices for management fees, maintenance tracking, and leasing services. Free PDF download."
  },
  {
    "slug": "roofing",
    "name": "Roofing",
    "title": "Free Roofing Invoice Template",
    "description": "Generate roofing invoices for shingle replacement, inspections, and weatherproofing. Free PDF download — no sign-up."
  },
  {
    "slug": "software-development",
    "name": "Software Development",
    "title": "Free Software Development Invoice Template",
    "description": "Create software development invoices for sprints, features, and maintenance. Free PDF download — no sign-up."
  },
  {
    "slug": "tattoo-artist",
    "name": "Tattoo Artist",
    "title": "Free Tattoo Artist Invoice Template",
    "description": "Create tattoo artist invoices for sessions, custom drawings, and deposits. Free PDF download — no sign-up."
  },
  {
    "slug": "towing",
    "name": "Towing & Roadside",
    "title": "Free Towing Invoice Template",
    "description": "Create towing and roadside assistance invoices for vehicle recovery, jump starts, and transport. Free PDF download."
  },
  {
    "slug": "translation",
    "name": "Translation Services",
    "title": "Free Translation Invoice Template",
    "description": "Create translation service invoices for per-word rates, certified documents, and interpretation. Free PDF download."
  },
  {
    "slug": "transport",
    "name": "Transport & Freight",
    "title": "Free Transport Invoice Template",
    "description": "Create transport and freight invoices for hauling, delivery, and logistics services. Free PDF download."
  },
  {
    "slug": "videography",
    "name": "Videography",
    "title": "Free Videography Invoice Template",
    "description": "Create videography invoices for shoots, editing, and post-production. Free PDF download — no sign-up."
  },
  {
    "slug": "virtual-assistant",
    "name": "Virtual Assistant",
    "title": "Free Virtual Assistant Invoice Template",
    "description": "Create virtual assistant invoices for admin hours, inbox management, and retainer billing. Free PDF download."
  },
  {
    "slug": "web-design",
    "name": "Web Design",
    "title": "Web Design Invoice Template",
    "description": "Bill for web design and development projects with a professional invoice. Covers design, development, hosting, and maintenance."
  }
];
